[Infra] check function of win runner
check function of new added win runner

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -13,249 +13,249 @@ defaults:
     working-directory: lynx
 
 jobs:
-  static-check:
-    runs-on: lynx-ubuntu-22.04-avd-medium
-    steps:
-      - name: Python Setup
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.13'
-      - name: Download Source
-        uses: actions/checkout@v4.2.2
-        with:
-          fetch-depth: 2
-          ref: ${{ github.event.pull_request.head.sha }}
-          path: lynx
-      - name: Install Common Dependencies
-        uses: ./lynx/.github/actions/common-deps
-      - name: Run file type check
-        run: |
-          source tools/envsetup.sh
-          python3 tools_shared/git_lynx.py check --checkers file-type
-      - name: Run cpplint check
-        run: |
-          source tools/envsetup.sh
-          python3 tools_shared/git_lynx.py check --checkers cpplint
-      - name: Run java-lint check
-        run: |
-          source tools/envsetup.sh
-          python3 tools_shared/git_lynx.py check --checkers java-lint
-      - name: Run commit-message check
-        run: |
-          source tools/envsetup.sh
-          python3 tools_shared/git_lynx.py check --checkers commit-message
-      - name: Run coding-style check
-        run: |
-          source tools/envsetup.sh
-          python3 tools_shared/git_lynx.py check --checkers coding-style
-      - name: Run android-check-style check
-        run: |
-          source tools/envsetup.sh
-          python3 tools_shared/git_lynx.py check --checkers android-check-style
-      - name: Run api check
-        run: |
-          source tools/envsetup.sh
-          python3 tools_shared/git_lynx.py check --checkers api-check
+  # static-check:
+  #   runs-on: lynx-ubuntu-22.04-avd-medium
+  #   steps:
+  #     - name: Python Setup
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: '3.13'
+  #     - name: Download Source
+  #       uses: actions/checkout@v4.2.2
+  #       with:
+  #         fetch-depth: 2
+  #         ref: ${{ github.event.pull_request.head.sha }}
+  #         path: lynx
+  #     - name: Install Common Dependencies
+  #       uses: ./lynx/.github/actions/common-deps
+  #     - name: Run file type check
+  #       run: |
+  #         source tools/envsetup.sh
+  #         python3 tools_shared/git_lynx.py check --checkers file-type
+  #     - name: Run cpplint check
+  #       run: |
+  #         source tools/envsetup.sh
+  #         python3 tools_shared/git_lynx.py check --checkers cpplint
+  #     - name: Run java-lint check
+  #       run: |
+  #         source tools/envsetup.sh
+  #         python3 tools_shared/git_lynx.py check --checkers java-lint
+  #     - name: Run commit-message check
+  #       run: |
+  #         source tools/envsetup.sh
+  #         python3 tools_shared/git_lynx.py check --checkers commit-message
+  #     - name: Run coding-style check
+  #       run: |
+  #         source tools/envsetup.sh
+  #         python3 tools_shared/git_lynx.py check --checkers coding-style
+  #     - name: Run android-check-style check
+  #       run: |
+  #         source tools/envsetup.sh
+  #         python3 tools_shared/git_lynx.py check --checkers android-check-style
+  #     - name: Run api check
+  #       run: |
+  #         source tools/envsetup.sh
+  #         python3 tools_shared/git_lynx.py check --checkers api-check
 
-  darwin-native-unittests-check:
-    runs-on: lynx-darwin-14-medium
-    steps:
-      - name: Download Source
-        uses: actions/checkout@v4.2.2
-        with:
-          path: lynx
-      - name: Install Common Dependencies
-        uses: ./lynx/.github/actions/common-deps
-      - name: Run Unittests
-        run: |
-          set -e
-          source tools/envsetup.sh
-          tools/rtf/rtf native-ut run --names lynx
+  # darwin-native-unittests-check:
+  #   runs-on: lynx-darwin-14-medium
+  #   steps:
+  #     - name: Download Source
+  #       uses: actions/checkout@v4.2.2
+  #       with:
+  #         path: lynx
+  #     - name: Install Common Dependencies
+  #       uses: ./lynx/.github/actions/common-deps
+  #     - name: Run Unittests
+  #       run: |
+  #         set -e
+  #         source tools/envsetup.sh
+  #         tools/rtf/rtf native-ut run --names lynx
 
-  linux-native-unittests-check:
-    runs-on: lynx-ubuntu-22.04-avd-large
-    steps:
-      - name: Download Source
-        uses: actions/checkout@v4.2.2
-        with:
-          path: lynx
-      - name: Python Setup
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.13'
-      - name: Install Common Dependencies
-        uses: ./lynx/.github/actions/common-deps
-      - name: Run Unittests
-        run: |
-          set -e
-          source tools/envsetup.sh
-          tools/rtf/rtf native-ut run --names lynx
+  # linux-native-unittests-check:
+  #   runs-on: lynx-ubuntu-22.04-avd-large
+  #   steps:
+  #     - name: Download Source
+  #       uses: actions/checkout@v4.2.2
+  #       with:
+  #         path: lynx
+  #     - name: Python Setup
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: '3.13'
+  #     - name: Install Common Dependencies
+  #       uses: ./lynx/.github/actions/common-deps
+  #     - name: Run Unittests
+  #       run: |
+  #         set -e
+  #         source tools/envsetup.sh
+  #         tools/rtf/rtf native-ut run --names lynx
 
-  linux-native-devtool-unittests-check:
-    runs-on: lynx-ubuntu-22.04-avd-large
-    steps:
-      - name: Download Source
-        uses: actions/checkout@v4.2.2
-        with:
-          path: lynx
-      - name: Python Setup
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.13'
-      - name: Install Common Dependencies
-        uses: ./lynx/.github/actions/common-deps
-      - name: Run Unittests
-        run: |
-          set -e
-          source tools/envsetup.sh
-          tools/rtf/rtf native-ut run --names devtool
+  # linux-native-devtool-unittests-check:
+  #   runs-on: lynx-ubuntu-22.04-avd-large
+  #   steps:
+      # - name: Download Source
+      #   uses: actions/checkout@v4.2.2
+      #   with:
+      #     path: lynx
+      # - name: Python Setup
+      #   uses: actions/setup-python@v5
+      #   with:
+      #     python-version: '3.13'
+      # - name: Install Common Dependencies
+      #   uses: ./lynx/.github/actions/common-deps
+      # - name: Run Unittests
+      #   run: |
+      #     set -e
+      #     source tools/envsetup.sh
+          # tools/rtf/rtf native-ut run --names devtool
 
-  ios-unittests-check:
-    runs-on: lynx-darwin-14-medium
-    steps:
-      - name: Download Source
-        uses: actions/checkout@v4.2.2
-        with:
-          path: lynx
-      - name: Install Common Dependencies
-        uses: ./lynx/.github/actions/common-deps
-      - name: Setup Ruby Cache
-        uses: ./lynx/.github/actions/ios-common-deps
-      - name: Install iOS Dependencies
-        uses: nick-fields/retry@v2
-        with:
-          timeout_minutes: 20
-          max_attempts: 3
-          command: |
-            set -e
-            cd $GITHUB_WORKSPACE/lynx
-            source tools/envsetup.sh
-            pushd explorer/darwin/ios/lynx_explorer
-            git config --global url."https://github.com/".insteadOf "git@github.com:"
-            bash bundle_install.sh --skip-card-build
-            popd
-      - name: Run Unittests
-        run: |
-          set -e
-          source tools/envsetup.sh
-          pushd explorer/darwin/ios/lynx_explorer
-          xcodebuild -showsdks | grep -Eo -m 1 "iphonesimulator([0-9]{1,}\.)+[0-9]{1,}" > sdk.txt
-          sdkVersion=$(awk '{ sub(/iphonesimulator/,""); print $0 }' sdk.txt)
-          echo $sdkVersion > sdk.txt
-          xcodebuild build-for-testing ARCHS=arm64 -workspace LynxExplorer.xcworkspace -scheme LynxExplorerTests -enableCodeCoverage YES -configuration Debug -sdk iphonesimulator$(cat sdk.txt) COMPILER_INDEX_STORE_ENABLE=NO -derivedDataPath iOSCoreBuild/DerivedData -dest"platform=iOS Simulator,OS=$(cat sdk.txt),name=iPhone 11" SYMROOT=`pwd`/Build/Products -testPlan UTTest
-          chmod u+x xctestrunner
-          ./xctestrunner --xctestrun `pwd`/Build/Products/LynxExplorerTests_UTTest_iphonesimulator$(cat sdk.txt)-arm64.xctestrun --work_dir `pwd` --output_dir `pwd`/iOSCoreBuild/DerivedData simulator_test
-          popd
+  # ios-unittests-check:
+  #   runs-on: lynx-darwin-14-medium
+  #   steps:
+  #     - name: Download Source
+  #       uses: actions/checkout@v4.2.2
+  #       with:
+  #         path: lynx
+  #     - name: Install Common Dependencies
+  #       uses: ./lynx/.github/actions/common-deps
+  #     - name: Setup Ruby Cache
+  #       uses: ./lynx/.github/actions/ios-common-deps
+  #     - name: Install iOS Dependencies
+  #       uses: nick-fields/retry@v2
+  #       with:
+  #         timeout_minutes: 20
+  #         max_attempts: 3
+  #         command: |
+  #           set -e
+  #           cd $GITHUB_WORKSPACE/lynx
+  #           source tools/envsetup.sh
+  #           pushd explorer/darwin/ios/lynx_explorer
+  #           git config --global url."https://github.com/".insteadOf "git@github.com:"
+  #           bash bundle_install.sh --skip-card-build
+  #           popd
+  #     - name: Run Unittests
+  #       run: |
+  #         set -e
+  #         source tools/envsetup.sh
+  #         pushd explorer/darwin/ios/lynx_explorer
+  #         xcodebuild -showsdks | grep -Eo -m 1 "iphonesimulator([0-9]{1,}\.)+[0-9]{1,}" > sdk.txt
+  #         sdkVersion=$(awk '{ sub(/iphonesimulator/,""); print $0 }' sdk.txt)
+  #         echo $sdkVersion > sdk.txt
+  #         xcodebuild build-for-testing ARCHS=arm64 -workspace LynxExplorer.xcworkspace -scheme LynxExplorerTests -enableCodeCoverage YES -configuration Debug -sdk iphonesimulator$(cat sdk.txt) COMPILER_INDEX_STORE_ENABLE=NO -derivedDataPath iOSCoreBuild/DerivedData -dest"platform=iOS Simulator,OS=$(cat sdk.txt),name=iPhone 11" SYMROOT=`pwd`/Build/Products -testPlan UTTest
+  #         chmod u+x xctestrunner
+  #         ./xctestrunner --xctestrun `pwd`/Build/Products/LynxExplorerTests_UTTest_iphonesimulator$(cat sdk.txt)-arm64.xctestrun --work_dir `pwd` --output_dir `pwd`/iOSCoreBuild/DerivedData simulator_test
+  #         popd
 
-  tasm-linux-build:
-    runs-on: lynx-ubuntu-22.04-avd-large
-    steps:
-      - name: Download Source
-        uses: actions/checkout@v4.2.2
-        with:
-          path: lynx
-      - name: Python Setup
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.13'
-      - name: Install Common Dependencies
-        uses: ./lynx/.github/actions/common-deps
-      - name: Build Linux Tasm
-        run: |
-          source tools/envsetup.sh
-          tools/hab sync . -f
-          pushd oliver/lynx-tasm
-          npm install
-          npm run build:release:linux
-          popd
+  # tasm-linux-build:
+  #   runs-on: lynx-ubuntu-22.04-avd-large
+  #   steps:
+  #     - name: Download Source
+  #       uses: actions/checkout@v4.2.2
+  #       with:
+  #         path: lynx
+  #     - name: Python Setup
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: '3.13'
+  #     - name: Install Common Dependencies
+  #       uses: ./lynx/.github/actions/common-deps
+  #     - name: Build Linux Tasm
+  #       run: |
+  #         source tools/envsetup.sh
+  #         tools/hab sync . -f
+  #         pushd oliver/lynx-tasm
+  #         npm install
+  #         npm run build:release:linux
+  #         popd
 
-  tasm-darwin-build:
-    runs-on: lynx-darwin-14-medium
-    steps:
-      - name: Download Source
-        uses: actions/checkout@v4.2.2
-        with:
-          path: lynx
-      - name: Install Common Dependencies
-        uses: ./lynx/.github/actions/common-deps
-      - name: Build Darwin Tasm
-        run: |
-          source tools/envsetup.sh
-          tools/hab sync . -f
-          pushd oliver/lynx-tasm
-          npm install
-          npm run build:release:darwin
-          popd
+  # tasm-darwin-build:
+  #   runs-on: lynx-darwin-14-medium
+  #   steps:
+  #     - name: Download Source
+  #       uses: actions/checkout@v4.2.2
+  #       with:
+  #         path: lynx
+  #     - name: Install Common Dependencies
+  #       uses: ./lynx/.github/actions/common-deps
+  #     - name: Build Darwin Tasm
+  #       run: |
+  #         source tools/envsetup.sh
+  #         tools/hab sync . -f
+  #         pushd oliver/lynx-tasm
+  #         npm install
+  #         npm run build:release:darwin
+  #         popd
 
-  tasm-wasm-build:
-    runs-on: lynx-darwin-14-medium
-    steps:
-      - name: Download Source
-        uses: actions/checkout@v4.2.2
-        with:
-          path: lynx
-      - name: Install Common Dependencies
-        uses: ./lynx/.github/actions/common-deps
-      - name: Build Wasm Tasm
-        run: |
-          source tools/envsetup.sh
-          tools/hab sync . -f --target tasm
-          pushd oliver/lynx-tasm
-          npm install
-          npm run build:wasm
-          popd
+  # tasm-wasm-build:
+  #   runs-on: lynx-darwin-14-medium
+  #   steps:
+  #     - name: Download Source
+  #       uses: actions/checkout@v4.2.2
+  #       with:
+  #         path: lynx
+  #     - name: Install Common Dependencies
+  #       uses: ./lynx/.github/actions/common-deps
+  #     - name: Build Wasm Tasm
+  #       run: |
+  #         source tools/envsetup.sh
+  #         tools/hab sync . -f --target tasm
+  #         pushd oliver/lynx-tasm
+  #         npm install
+  #         npm run build:wasm
+  #         popd
 
-  lynx-types-check:
-    runs-on: lynx-ubuntu-22.04-avd-medium
-    steps:
-      - name: Download Source
-        uses: actions/checkout@v4.2.2
-        with:
-          path: lynx
-      - name: Python Setup
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.13'
-      - name: Install Common Dependencies
-        uses: ./lynx/.github/actions/common-deps
-      - name: Lynx Types Check
-        run: |
-          cd $GITHUB_WORKSPACE/lynx
-          source tools/envsetup.sh
-          pushd js_libraries/types
-          npm run test
-          popd
+  # lynx-types-check:
+  #   runs-on: lynx-ubuntu-22.04-avd-medium
+  #   steps:
+  #     - name: Download Source
+  #       uses: actions/checkout@v4.2.2
+  #       with:
+  #         path: lynx
+  #     - name: Python Setup
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: '3.13'
+  #     - name: Install Common Dependencies
+  #       uses: ./lynx/.github/actions/common-deps
+  #     - name: Lynx Types Check
+  #       run: |
+  #         cd $GITHUB_WORKSPACE/lynx
+  #         source tools/envsetup.sh
+  #         pushd js_libraries/types
+  #         npm run test
+  #         popd
 
-  android-unittests-check:
-    runs-on: lynx-ubuntu-22.04-physical-medium
-    steps:
-      - name: Download Source
-        uses: actions/checkout@v4.2.2
-        with:
-          path: lynx
-      - name: Python Setup
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.13'
-      - name: Install Common Dependencies
-        uses: ./lynx/.github/actions/common-deps
-      - name: Build Example App
-        run: |
-          source tools/envsetup.sh
-          tools/rtf/rtf android-ut run --name lynx
+  # android-unittests-check:
+  #   runs-on: lynx-ubuntu-22.04-physical-medium
+  #   steps:
+  #     - name: Download Source
+  #       uses: actions/checkout@v4.2.2
+  #       with:
+  #         path: lynx
+  #     - name: Python Setup
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: '3.13'
+  #     - name: Install Common Dependencies
+  #       uses: ./lynx/.github/actions/common-deps
+  #     - name: Build Example App
+  #       run: |
+  #         source tools/envsetup.sh
+  #         tools/rtf/rtf android-ut run --name lynx
 
-  android-explorer-build:
-    runs-on: lynx-ubuntu-22.04-avd-large
-    steps:
-      - name: Download Source
-        uses: actions/checkout@v4.2.2
-        with:
-          path: lynx
-      - name: Build Explorer App
-        uses: ./lynx/.github/actions/android-explorer-build
-        with:
-          build-type: dry-run
-          build-params: -PIntegrationTest
+  # android-explorer-build:
+  #   runs-on: lynx-ubuntu-22.04-avd-large
+  #   steps:
+  #     - name: Download Source
+  #       uses: actions/checkout@v4.2.2
+  #       with:
+  #         path: lynx
+  #     - name: Build Explorer App
+  #       uses: ./lynx/.github/actions/android-explorer-build
+  #       with:
+  #         build-type: dry-run
+  #         build-params: -PIntegrationTest
 
   # android-e2e-test:
   #   needs: [android-explorer-build]
@@ -407,8 +407,26 @@ jobs:
   #           popd
   #         fi
 
-  release-workflow:
-    uses: ./.github/workflows/publish-release.yml
-    with:
-      dry-run: true
-    secrets: inherit
+  # release-workflow:
+  #   uses: ./.github/workflows/publish-release.yml
+  #   with:
+  #     dry-run: true
+  #   secrets: inherit
+
+  windows-check:
+    runs-on: lynx-windows-2022-large
+    steps:
+      - name: Python Setup
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.13'
+      - name: Download Source
+        uses: actions/checkout@v4.2.2
+        with:
+          fetch-depth: 2
+          ref: ${{ github.event.pull_request.head.sha }}
+          path: lynx
+      - name: Run windows check
+        run: |
+          $PSVersionTable.PSVersion -ne $null
+          Start-Sleep -Seconds 21600
