[Infra] debug xlarge
debug xlarge runner

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,7 +14,7 @@ defaults:
 
 jobs:
   static-check:
-    runs-on: lynx-ubuntu-22.04-medium
+    runs-on: lynx-ubuntu-24.04-xlarge
     timeout-minutes: 30
     steps:
       - name: Python Setup
@@ -58,102 +58,102 @@ jobs:
           source tools/envsetup.sh
           python3 tools_shared/git_lynx.py check --checkers api-check
 
-  darwin-native-unittests-check:
-    timeout-minutes: 60
-    runs-on: lynx-darwin-14-medium
-    steps:
-      - name: Download Source
-        uses: actions/checkout@v4.2.2
-        with:
-          path: lynx
-      - name: Install Common Dependencies
-        uses: ./lynx/.github/actions/common-deps
-      - name: Run Unittests
-        run: |
-          set -e
-          source tools/envsetup.sh
-          tools/rtf/rtf native-ut run --names lynx
+  # darwin-native-unittests-check:
+  #   timeout-minutes: 60
+  #   runs-on: lynx-darwin-14-medium
+  #   steps:
+  #     - name: Download Source
+  #       uses: actions/checkout@v4.2.2
+  #       with:
+  #         path: lynx
+  #     - name: Install Common Dependencies
+  #       uses: ./lynx/.github/actions/common-deps
+  #     - name: Run Unittests
+  #       run: |
+  #         set -e
+  #         source tools/envsetup.sh
+  #         tools/rtf/rtf native-ut run --names lynx
 
-  linux-native-unittests-check:
-    runs-on: lynx-ubuntu-22.04-large
-    timeout-minutes: 60
-    steps:
-      - name: Download Source
-        uses: actions/checkout@v4.2.2
-        with:
-          path: lynx
-      - name: Python Setup
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.13'
-      - name: Install Common Dependencies
-        uses: ./lynx/.github/actions/common-deps
-      - name: Run Unittests
-        run: |
-          set -e
-          source tools/envsetup.sh
-          tools/rtf/rtf native-ut run --names lynx
+  # linux-native-unittests-check:
+  #   runs-on: lynx-ubuntu-22.04-large
+  #   timeout-minutes: 60
+  #   steps:
+  #     - name: Download Source
+  #       uses: actions/checkout@v4.2.2
+  #       with:
+  #         path: lynx
+  #     - name: Python Setup
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: '3.13'
+  #     - name: Install Common Dependencies
+  #       uses: ./lynx/.github/actions/common-deps
+  #     - name: Run Unittests
+  #       run: |
+  #         set -e
+  #         source tools/envsetup.sh
+  #         tools/rtf/rtf native-ut run --names lynx
 
-  linux-native-devtool-unittests-check:
-    runs-on: lynx-ubuntu-22.04-large
-    timeout-minutes: 60
-    steps:
-      - name: Download Source
-        uses: actions/checkout@v4.2.2
-        with:
-          path: lynx
-      - name: Python Setup
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.13'
-      - name: Install Common Dependencies
-        uses: ./lynx/.github/actions/common-deps
-      - name: Run Unittests
-        run: |
-          set -e
-          source tools/envsetup.sh
-          tools/rtf/rtf native-ut run --names devtool
+  # linux-native-devtool-unittests-check:
+  #   runs-on: lynx-ubuntu-22.04-large
+  #   timeout-minutes: 60
+  #   steps:
+  #     - name: Download Source
+  #       uses: actions/checkout@v4.2.2
+  #       with:
+  #         path: lynx
+  #     - name: Python Setup
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: '3.13'
+  #     - name: Install Common Dependencies
+  #       uses: ./lynx/.github/actions/common-deps
+  #     - name: Run Unittests
+  #       run: |
+  #         set -e
+  #         source tools/envsetup.sh
+  #         tools/rtf/rtf native-ut run --names devtool
 
-  ios-unittests-check:
-    timeout-minutes: 60
-    runs-on: lynx-darwin-14-medium
-    steps:
-      - name: Download Source
-        uses: actions/checkout@v4.2.2
-        with:
-          path: lynx
-      - name: Install Common Dependencies
-        uses: ./lynx/.github/actions/common-deps
-      - name: Setup Ruby Cache
-        uses: ./lynx/.github/actions/ios-common-deps
-      - name: Install iOS Dependencies
-        uses: nick-fields/retry@v2
-        with:
-          timeout_minutes: 20
-          max_attempts: 3
-          command: |
-            set -e
-            cd $GITHUB_WORKSPACE/lynx
-            source tools/envsetup.sh
-            pushd explorer/darwin/ios/lynx_explorer
-            git config --global url."https://github.com/".insteadOf "git@github.com:"
-            bash bundle_install.sh --skip-card-build
-            popd
-      - name: Run Unittests
-        run: |
-          set -e
-          source tools/envsetup.sh
-          pushd explorer/darwin/ios/lynx_explorer
-          xcodebuild -showsdks | grep -Eo -m 1 "iphonesimulator([0-9]{1,}\.)+[0-9]{1,}" > sdk.txt
-          sdkVersion=$(awk '{ sub(/iphonesimulator/,""); print $0 }' sdk.txt)
-          echo $sdkVersion > sdk.txt
-          xcodebuild build-for-testing ARCHS=arm64 -workspace LynxExplorer.xcworkspace -scheme LynxExplorerTests -enableCodeCoverage YES -configuration Debug -sdk iphonesimulator$(cat sdk.txt) COMPILER_INDEX_STORE_ENABLE=NO -derivedDataPath iOSCoreBuild/DerivedData -dest"platform=iOS Simulator,OS=$(cat sdk.txt),name=iPhone 11" SYMROOT=`pwd`/Build/Products -testPlan UTTest
-          chmod u+x xctestrunner
-          ./xctestrunner --xctestrun `pwd`/Build/Products/LynxExplorerTests_UTTest_iphonesimulator$(cat sdk.txt)-arm64.xctestrun --work_dir `pwd` --output_dir `pwd`/iOSCoreBuild/DerivedData simulator_test
-          popd
+  # ios-unittests-check:
+  #   timeout-minutes: 60
+  #   runs-on: lynx-darwin-14-medium
+  #   steps:
+  #     - name: Download Source
+  #       uses: actions/checkout@v4.2.2
+  #       with:
+  #         path: lynx
+  #     - name: Install Common Dependencies
+  #       uses: ./lynx/.github/actions/common-deps
+  #     - name: Setup Ruby Cache
+  #       uses: ./lynx/.github/actions/ios-common-deps
+  #     - name: Install iOS Dependencies
+  #       uses: nick-fields/retry@v2
+  #       with:
+  #         timeout_minutes: 20
+  #         max_attempts: 3
+  #         command: |
+  #           set -e
+  #           cd $GITHUB_WORKSPACE/lynx
+  #           source tools/envsetup.sh
+  #           pushd explorer/darwin/ios/lynx_explorer
+  #           git config --global url."https://github.com/".insteadOf "git@github.com:"
+  #           bash bundle_install.sh --skip-card-build
+  #           popd
+  #     - name: Run Unittests
+  #       run: |
+  #         set -e
+  #         source tools/envsetup.sh
+  #         pushd explorer/darwin/ios/lynx_explorer
+  #         xcodebuild -showsdks | grep -Eo -m 1 "iphonesimulator([0-9]{1,}\.)+[0-9]{1,}" > sdk.txt
+  #         sdkVersion=$(awk '{ sub(/iphonesimulator/,""); print $0 }' sdk.txt)
+  #         echo $sdkVersion > sdk.txt
+  #         xcodebuild build-for-testing ARCHS=arm64 -workspace LynxExplorer.xcworkspace -scheme LynxExplorerTests -enableCodeCoverage YES -configuration Debug -sdk iphonesimulator$(cat sdk.txt) COMPILER_INDEX_STORE_ENABLE=NO -derivedDataPath iOSCoreBuild/DerivedData -dest"platform=iOS Simulator,OS=$(cat sdk.txt),name=iPhone 11" SYMROOT=`pwd`/Build/Products -testPlan UTTest
+  #         chmod u+x xctestrunner
+  #         ./xctestrunner --xctestrun `pwd`/Build/Products/LynxExplorerTests_UTTest_iphonesimulator$(cat sdk.txt)-arm64.xctestrun --work_dir `pwd` --output_dir `pwd`/iOSCoreBuild/DerivedData simulator_test
+  #         popd
 
   tasm-linux-build:
-    runs-on: lynx-ubuntu-22.04-large
+    runs-on: lynx-ubuntu-24.04-xlarge
     timeout-minutes: 60
     steps:
       - name: Download Source
@@ -175,43 +175,43 @@ jobs:
           npm run build:release:linux
           popd
 
-  tasm-darwin-build:
-    timeout-minutes: 60
-    runs-on: lynx-darwin-14-medium
-    steps:
-      - name: Download Source
-        uses: actions/checkout@v4.2.2
-        with:
-          path: lynx
-      - name: Install Common Dependencies
-        uses: ./lynx/.github/actions/common-deps
-      - name: Build Darwin Tasm
-        run: |
-          source tools/envsetup.sh
-          tools/hab sync . -f
-          pushd oliver/lynx-tasm
-          npm install
-          npm run build:release:darwin
-          popd
+  # tasm-darwin-build:
+  #   timeout-minutes: 60
+  #   runs-on: lynx-darwin-14-medium
+  #   steps:
+  #     - name: Download Source
+  #       uses: actions/checkout@v4.2.2
+  #       with:
+  #         path: lynx
+  #     - name: Install Common Dependencies
+  #       uses: ./lynx/.github/actions/common-deps
+  #     - name: Build Darwin Tasm
+  #       run: |
+  #         source tools/envsetup.sh
+  #         tools/hab sync . -f
+  #         pushd oliver/lynx-tasm
+  #         npm install
+  #         npm run build:release:darwin
+  #         popd
 
-  tasm-wasm-build:
-    timeout-minutes: 60
-    runs-on: lynx-darwin-14-medium
-    steps:
-      - name: Download Source
-        uses: actions/checkout@v4.2.2
-        with:
-          path: lynx
-      - name: Install Common Dependencies
-        uses: ./lynx/.github/actions/common-deps
-      - name: Build Wasm Tasm
-        run: |
-          source tools/envsetup.sh
-          tools/hab sync . -f --target tasm
-          pushd oliver/lynx-tasm
-          npm install
-          npm run build:wasm
-          popd
+  # tasm-wasm-build:
+  #   timeout-minutes: 60
+  #   runs-on: lynx-darwin-14-medium
+  #   steps:
+  #     - name: Download Source
+  #       uses: actions/checkout@v4.2.2
+  #       with:
+  #         path: lynx
+  #     - name: Install Common Dependencies
+  #       uses: ./lynx/.github/actions/common-deps
+  #     - name: Build Wasm Tasm
+  #       run: |
+  #         source tools/envsetup.sh
+  #         tools/hab sync . -f --target tasm
+  #         pushd oliver/lynx-tasm
+  #         npm install
+  #         npm run build:wasm
+  #         popd
 
   lynx-types-check:
     runs-on: lynx-ubuntu-22.04-medium
@@ -235,38 +235,38 @@ jobs:
           npm run test
           popd
 
-  android-unittests-check:
-    timeout-minutes: 60
-    runs-on: lynx-ubuntu-22.04-physical-medium
-    steps:
-      - name: Download Source
-        uses: actions/checkout@v4.2.2
-        with:
-          path: lynx
-      - name: Python Setup
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.13'
-      - name: Install Common Dependencies
-        uses: ./lynx/.github/actions/common-deps
-      - name: Build Example App
-        run: |
-          source tools/envsetup.sh
-          tools/rtf/rtf android-ut run --name lynx
+  # android-unittests-check:
+  #   timeout-minutes: 60
+  #   runs-on: lynx-ubuntu-22.04-physical-medium
+  #   steps:
+  #     - name: Download Source
+  #       uses: actions/checkout@v4.2.2
+  #       with:
+  #         path: lynx
+  #     - name: Python Setup
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: '3.13'
+  #     - name: Install Common Dependencies
+  #       uses: ./lynx/.github/actions/common-deps
+  #     - name: Build Example App
+  #       run: |
+  #         source tools/envsetup.sh
+  #         tools/rtf/rtf android-ut run --name lynx
 
-  android-explorer-build:
-    runs-on: lynx-ubuntu-22.04-large
-    timeout-minutes: 60
-    steps:
-      - name: Download Source
-        uses: actions/checkout@v4.2.2
-        with:
-          path: lynx
-      - name: Build Explorer App
-        uses: ./lynx/.github/actions/android-explorer-build
-        with:
-          build-type: dry-run
-          build-params: -PIntegrationTest
+  # android-explorer-build:
+  #   runs-on: lynx-ubuntu-22.04-large
+  #   timeout-minutes: 60
+  #   steps:
+  #     - name: Download Source
+  #       uses: actions/checkout@v4.2.2
+  #       with:
+  #         path: lynx
+  #     - name: Build Explorer App
+  #       uses: ./lynx/.github/actions/android-explorer-build
+  #       with:
+  #         build-type: dry-run
+  #         build-params: -PIntegrationTest
 
   # android-e2e-test:
   #   timeout-minutes: 60
@@ -419,8 +419,8 @@ jobs:
   #           popd
   #         fi
 
-  release-workflow:
-    uses: ./.github/workflows/publish-release.yml
-    with:
-      dry-run: true
-    secrets: inherit
+  # release-workflow:
+  #   uses: ./.github/workflows/publish-release.yml
+  #   with:
+  #     dry-run: true
+  #   secrets: inherit
